# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
  - nightly
matrix:
  allow_failures:
    - julia: nightly
sudo: required
dist: trusty
env:
  # Make PyCall use the right python version (where dolfin is installed)
  - PYTHON=/usr/bin/python2
before_install:
  # Install FEniCS (but don't do an 'apt-get upgrade' as this will timeout the process)
  - sudo add-apt-repository ppa:fenics-packages/fenics -y
  - sudo apt-get update -q
  - sudo apt-get install fenics -y
  #- docker pull quay.io/fenicsproject/stable:latest
  #- docker run -ti quay.io/fenicsproject/stable:latest
notifications:
  email: false
# uncomment the following lines to override the default test script
#script:
#  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
#  - julia -e 'Pkg.clone(pwd()); Pkg.build("FEniCS"); Pkg.test("FEniCS"; coverage=true)'
after_success:
  # push coverage results to Coveralls
  - julia -e 'cd(Pkg.dir("FEniCS")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
  # push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("FEniCS")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
