"""
    Geometry

Abstract wrapper for an mshr constructive-solid-geometry object.
"""
abstract type Geometry <: fenicsobject end

struct GeometryImpl <: Geometry
    pyobject::PyObject
end

Geometry(pyobject::PyObject) = GeometryImpl(pyobject)

#functions necessary for creating meshes from geometrical objects.
#2D objects below
"""
    Circle(centre, radius)

Create a two-dimensional mshr circle geometry.

# Arguments

- `centre`: Circle center accepted by mshr.
- `radius`: Circle radius.
"""
Circle(centre, radius) = Geometry(mshr.Circle(centre, radius))

"""
    Rectangle(corner1, corner2)

Create a two-dimensional mshr rectangle from opposite corners.

# Arguments

- `corner1`, `corner2`: Opposite rectangle corners accepted by mshr.
"""
Rectangle(corner1, corner2) = Geometry(mshr.Rectangle(corner1, corner2))

"""
    Ellipse(centre, horizontal_semi_axis, vertical_semi_axis, fragments)

Create a two-dimensional mshr ellipse geometry.

# Arguments

- `centre`: Ellipse center accepted by mshr.
- `horizontal_semi_axis`: Horizontal semi-axis length.
- `vertical_semi_axis`: Vertical semi-axis length.
- `fragments`: Number of fragments used to discretize the ellipse.
"""
function Ellipse(centre, horizontal_semi_axis, vertical_semi_axis, fragments)
    return Geometry(mshr.Ellipse(centre, horizontal_semi_axis, vertical_semi_axis, fragments))
end

#3d objects below
"""
    Box(corner1, corner2)

Create a three-dimensional mshr box from opposite corners.

# Arguments

- `corner1`, `corner2`: Opposite box corners accepted by mshr.
"""
Box(corner1, corner2) = Geometry(mshr.Box(corner1, corner2))

"""
    Cone(top, bottom, bottom_radius, slices)

Create a three-dimensional mshr cone geometry.

# Arguments

- `top`, `bottom`: Cone endpoints accepted by mshr.
- `bottom_radius`: Radius at the bottom endpoint.
- `slices`: Number of angular slices used to discretize the cone.
"""
function Cone(top, bottom, bottom_radius, slices::Int)
    return Geometry(mshr.Cone(top, bottom, bottom_radius, slices))
end
"""
    Sphere(centre, radius)

Create a three-dimensional mshr sphere geometry.

# Arguments

- `centre`: Sphere center accepted by mshr.
- `radius`: Sphere radius.
"""
Sphere(centre, radius) = Geometry(mshr.Sphere(centre, radius))

#we generate the mesh of some geometrical objects
"""
    generate_mesh(geom_object::Geometry, size::Int)

Generate a FEniCS mesh from an mshr geometry object.

# Arguments

- `geom_object`: Geometry to discretize.
- `size`: Target mesh resolution passed to mshr.

# Returns

A [`Mesh`](@ref) generated by mshr.
"""
function generate_mesh(geom_object::Geometry, size::Int)
    return Mesh(mshr.generate_mesh(geom_object.pyobject, size))
end
export Circle, Rectangle, Ellipse, Box, Cone, Sphere, generate_mesh

"""
    set_subdomain(object::Geometry, degree, domain2)

Set a subdomain marker on an mshr geometry object.

# Arguments

- `object`: Geometry whose subdomain is modified.
- `degree`: Subdomain degree passed to mshr.
- `domain2`: Subdomain object to assign.
"""
function set_subdomain(object::Geometry, degree, domain2)
    return fenicspycall(object, :set_subdomain, degree, domain2.pyobject)
end

"""
    Extrude2D(object::Geometry, thickness)

Extrude a two-dimensional geometry into three dimensions.

# Arguments

- `object`: Two-dimensional geometry to extrude.
- `thickness`: Extrusion thickness passed to mshr.
"""
function Extrude2D(object::Geometry, thickness)
    return Geometry(mshr.Extrude2D(object.pyobject, thickness))
end

function +(geom_object1::Geometry, geom_object2::Geometry)
    return Geometry(geom_object1.pyobject.__add__(geom_object2.pyobject))
end
function -(geom_object1::Geometry, geom_object2::Geometry)
    return Geometry(geom_object1.pyobject.__sub__(geom_object2.pyobject))
end
function *(geom_object1::Geometry, geom_object2::Geometry)
    return Geometry(geom_object1.pyobject.__mul__(geom_object2.pyobject))
end

export set_subdomain, Extrude2D

"""
    CSGUnion(geom_object1::Geometry, geom_object2::Geometry)

Construct the union of two mshr geometries.

# Arguments

- `geom_object1`, `geom_object2`: Geometries to combine.
"""
function CSGUnion(geom_object1::Geometry, geom_object2::Geometry)
    return Geometry(mshr.CSGUnion(geom_object1.pyobject, geom_object2.pyobject))
end
"""
    CSGIntersection(geom_object1::Geometry, geom_object2::Geometry)

Construct the intersection of two mshr geometries.

# Arguments

- `geom_object1`, `geom_object2`: Geometries to combine.
"""
function CSGIntersection(geom_object1::Geometry, geom_object2::Geometry)
    return Geometry(mshr.CSGIntersection(geom_object1.pyobject, geom_object2.pyobject))
end
"""
    CSGDifference(geom_object1::Geometry, geom_object2::Geometry)

Construct the difference of two mshr geometries.

# Arguments

- `geom_object1`: Geometry from which to subtract.
- `geom_object2`: Geometry to subtract.
"""
function CSGDifference(geom_object1::Geometry, geom_object2::Geometry)
    return Geometry(mshr.CSGDifference(geom_object1.pyobject, geom_object2.pyobject))
end

"""
    CSGScaling(geom_object1::Geometry, scale)

Scale an mshr geometry.

# Arguments

- `geom_object1`: Geometry to scale.
- `scale`: Scaling factor passed to mshr.
"""
function CSGScaling(geom_object1::Geometry, scale)
    return Geometry(mshr.CSGScaling(geom_object1.pyobject, scale))
end

"""
    CSGRotation(geom_object1::Geometry, angle)
    CSGRotation(geom_object1::Geometry, point, angle)
    CSGRotation(geom_object1::Geometry, point_axis, point_center, angle)

Rotate an mshr geometry using one of the supported rotation signatures.

# Arguments

- `geom_object1`: Geometry to rotate.
- `angle`: Rotation angle.
- `point`: Optional rotation point.
- `point_axis`: Optional rotation axis.
- `point_center`: Optional center of rotation.
"""
function CSGRotation(geom_object1::Geometry, angle)
    return Geometry(mshr.CSGRotation(geom_object1.pyobject, angle))
end
function CSGRotation(geom_object1::Geometry, point, angle)
    return Geometry(mshr.CSGRotation(geom_object1.pyobject, point, angle))
end
function CSGRotation(geom_object1::Geometry, point_axis, point_center, angle)
    return Geometry(mshr.CSGRotation(geom_object1.pyobject, point_axis, point_center, angle))
end

"""
    CSGTranslation(geom_object1::Geometry, translation_point)

Translate an mshr geometry.

# Arguments

- `geom_object1`: Geometry to translate.
- `translation_point`: Translation vector or point passed to mshr.
"""
function CSGTranslation(geom_object1::Geometry, translation_point)
    return Geometry(mshr.CSGTranslation(geom_object1.pyobject, translation_point))
end

export CSGUnion, CSGIntersection, CSGDifference, CSGScaling, CSGRotation, CSGTranslation
