name: Documentation

on:
  push:
    branches:
      - master
      - 'release-'
    tags: '*'
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/master' }}

jobs:
  documentation:
    uses: "SciML/.github/.github/workflows/documentation.yml@v1"
    with:
      runner: '"ubuntu-24.04"'
    secrets: "inherit"
